# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20160325_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(max_length=100, verbose_name='Verb of the action'),
        ),
    ]
