# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 02:41
from __future__ import unicode_literals

import django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20171011_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSONField to store addtional data'),
        ),
        migrations.RunSQL('ALTER TABLE "notify_notification" ALTER COLUMN "extra" TYPE JSONB USING extra::JSONB;')
    ]
